from .get_me import GetMeMethod
from .get_chat import GetChatMethod
from .get_chats import GetChatsMethod
from .send_message import SendMessageMethod
from .update_me import UpdateMeMethod
from .get_messages import GetMessagesMethod
from .upload import UploadMethod
from .delete_message import DeleteMessageMethod
from .edit_message import EditMessageMethod
from .get_message import GetMessageMethod
from .answer import AnswerMethod
from .get_video import GetVideoMethod
